In [54]:
import pandas as pd
import re

with open("sample_logs.txt", "r") as f:
    all_lines = f.readlines()

total_lines = len(all_lines)
non_empty_logs = [line.strip() for line in all_lines if line.strip()]
empty_lines = [line for line in all_lines if not line.strip()]

print("Total lines in file:", total_lines)
print("Non-empty logs:", len(non_empty_logs))
print("Empty/blank lines:", len(empty_lines))

df = pd.DataFrame({"raw_log": non_empty_logs})

# Basic cleaning
df['raw_log'] = df['raw_log'].str.lower()

display(df.head(10))

Total lines in file: 5200
Non-empty logs: 5195
Empty/blank lines: 5

                                                                                                                  raw_log
0                         mar 15 06:00:03 prod-app-01 api-gateway[3330]: <info> health check passed upstream=auth-service
1  2026-03-15 06:00:03 info  [api-gateway] request completed method=get path=/api/v2/users/3591 status=200 duration=264ms
2                                   2026-03-15 06:00:07 warn  [inventory] sync delay from erp: last update 47 minutes ago
3                                 2026-03-15 06:00:09 info  [inventory] stock updated sku=gw-7547 qty=328 warehouse=wh-03
4                           2026-03-15t06:00:11.927231z error auth-service: mfa verification failed uid=2160 code=invalid
5          2026-03-15 06:00:14 warn  [api-gateway] request slow method=get path=/api/v2/search status=200 duration=2021ms
6                                                            [06:00:17] i/auth-service: password reset requested uid=9085
7     mar 15 06:00:21 prod-app-01 inventory[4727]: <info> inventory sync completed source=erp records=2847 duration=12.4s
8                         [06:00:25] i/email-service: email sent to=user677@company.io template=welcome msg_id=msg-739098
9                   [06:00:28] i/api-gateway: request completed method=get path=/api/v2/products status=200 duration=49ms

In [55]:
import re

def normalize_log(log):
    log = log.lower()
    
    # Replace IP addresses
    log = re.sub(r'\b(?:\d{1,3}\.){3}\d{1,3}\b', '<IP>', log)
    
    # Replace URLs/paths
    log = re.sub(r'\/[^\s]+', '<PATH>', log)
    
    # Replace timestamps (common patterns)
    log = re.sub(r'\b\d{2}:\d{2}:\d{2}\b', '<TIME>', log)
    
    # Replace standalone numbers (but preserve meaning)
    log = re.sub(r'\b\d+\b', '<NUM>', log)
    
    # Clean extra spaces
    log = re.sub(r'\s+', ' ', log).strip()
    
    return log

df["normalized_log"] = df["raw_log"].apply(normalize_log)

print("Normalized logs preview:")
display(df[["raw_log", "normalized_log"]].head(10))

Normalized logs preview:

,raw_log,normalized_log
0,mar 15 06:00:03 prod-app-01 api-gateway[3330]: <info> health check passed upstream=auth-service,mar <NUM> <TIME> prod-app-<NUM> api-gateway[<NUM>]: <info> health check passed upstream=auth-service
1,2026-03-15 06:00:03 info [api-gateway] request completed method=get path=/api/v2/users/3591 status=200 duration=264ms,<NUM>-<NUM>-<NUM> <TIME> info [api-gateway] request completed method=get path=<PATH> status=<NUM> duration=264ms
2,2026-03-15 06:00:07 warn [inventory] sync delay from erp: last update 47 minutes ago,<NUM>-<NUM>-<NUM> <TIME> warn [inventory] sync delay from erp: last update <NUM> minutes ago
3,2026-03-15 06:00:09 info [inventory] stock updated sku=gw-7547 qty=328 warehouse=wh-03,<NUM>-<NUM>-<NUM> <TIME> info [inventory] stock updated sku=gw-<NUM> qty=<NUM> warehouse=wh-<NUM>
4,2026-03-15t06:00:11.927231z error auth-service: mfa verification failed uid=2160 code=invalid,<NUM>-<NUM>-15t06:<NUM>:<NUM>.927231z error auth-service: mfa verification failed uid=<NUM> code=invalid
5,2026-03-15 06:00:14 warn [api-gateway] request slow method=get path=/api/v2/search status=200 duration=2021ms,<NUM>-<NUM>-<NUM> <TIME> warn [api-gateway] request slow method=get path=<PATH> status=<NUM> duration=2021ms
6,[06:00:17] i/auth-service: password reset requested uid=9085,[<TIME>] i<PATH> password reset requested uid=<NUM>
7,mar 15 06:00:21 prod-app-01 inventory[4727]: <info> inventory sync completed source=erp records=2847 duration=12.4s,mar <NUM> <TIME> prod-app-<NUM> inventory[<NUM>]: <info> inventory sync completed source=erp records=<NUM> duration=<NUM>.4s
8,[06:00:25] i/email-service: email sent to=user677@company.io template=welcome msg_id=msg-739098,[<TIME>] i<PATH> email sent to=user677@company.io template=welcome msg_id=msg-<NUM>
9,[06:00:28] i/api-gateway: request completed method=get path=/api/v2/products status=200 duration=49ms,[<TIME>] i<PATH> request completed method=get path=<PATH> status=<NUM> duration=49ms

In [56]:
def generate_template(log):
    words = log.split()
    
    template = []
    for w in words:
        # Replace typed placeholders with generic wildcard
        if w in ['<ip>', '<path>', '<time>', '<num>']:
            template.append('*')
        else:
            template.append(w)
    
    return " ".join(template)

df["template"] = df["normalized_log"].apply(generate_template)

print("Template preview:")
display(df[["normalized_log", "template"]].head(10))

Template preview:

,normalized_log,template
0,mar <NUM> <TIME> prod-app-<NUM> api-gateway[<NUM>]: <info> health check passed upstream=auth-service,mar <NUM> <TIME> prod-app-<NUM> api-gateway[<NUM>]: <info> health check passed upstream=auth-service
1,<NUM>-<NUM>-<NUM> <TIME> info [api-gateway] request completed method=get path=<PATH> status=<NUM> duration=264ms,<NUM>-<NUM>-<NUM> <TIME> info [api-gateway] request completed method=get path=<PATH> status=<NUM> duration=264ms
2,<NUM>-<NUM>-<NUM> <TIME> warn [inventory] sync delay from erp: last update <NUM> minutes ago,<NUM>-<NUM>-<NUM> <TIME> warn [inventory] sync delay from erp: last update <NUM> minutes ago
3,<NUM>-<NUM>-<NUM> <TIME> info [inventory] stock updated sku=gw-<NUM> qty=<NUM> warehouse=wh-<NUM>,<NUM>-<NUM>-<NUM> <TIME> info [inventory] stock updated sku=gw-<NUM> qty=<NUM> warehouse=wh-<NUM>
4,<NUM>-<NUM>-15t06:<NUM>:<NUM>.927231z error auth-service: mfa verification failed uid=<NUM> code=invalid,<NUM>-<NUM>-15t06:<NUM>:<NUM>.927231z error auth-service: mfa verification failed uid=<NUM> code=invalid
5,<NUM>-<NUM>-<NUM> <TIME> warn [api-gateway] request slow method=get path=<PATH> status=<NUM> duration=2021ms,<NUM>-<NUM>-<NUM> <TIME> warn [api-gateway] request slow method=get path=<PATH> status=<NUM> duration=2021ms
6,[<TIME>] i<PATH> password reset requested uid=<NUM>,[<TIME>] i<PATH> password reset requested uid=<NUM>
7,mar <NUM> <TIME> prod-app-<NUM> inventory[<NUM>]: <info> inventory sync completed source=erp records=<NUM> duration=<NUM>.4s,mar <NUM> <TIME> prod-app-<NUM> inventory[<NUM>]: <info> inventory sync completed source=erp records=<NUM> duration=<NUM>.4s
8,[<TIME>] i<PATH> email sent to=user677@company.io template=welcome msg_id=msg-<NUM>,[<TIME>] i<PATH> email sent to=user677@company.io template=welcome msg_id=msg-<NUM>
9,[<TIME>] i<PATH> request completed method=get path=<PATH> status=<NUM> duration=49ms,[<TIME>] i<PATH> request completed method=get path=<PATH> status=<NUM> duration=49ms

In [57]:
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

# Step 1: Unique templates
unique_templates = df["template"].unique().tolist()

# Step 2: Generate embeddings for templates
model = SentenceTransformer('all-MiniLM-L6-v2')
template_embeddings = model.encode(unique_templates, show_progress_bar=True)

# Step 3: Compute similarity matrix
similarity_matrix = cosine_similarity(template_embeddings)

# Step 4: Merge similar templates based on threshold
SIM_THRESHOLD = 0.85

parent = list(range(len(unique_templates)))

def find(x):
    if parent[x] != x:
        parent[x] = find(parent[x])
    return parent[x]

def union(x, y):
    px, py = find(x), find(y)
    if px != py:
        parent[py] = px

for i in range(len(unique_templates)):
    for j in range(i + 1, len(unique_templates)):
        if similarity_matrix[i][j] >= SIM_THRESHOLD:
            union(i, j)

# Step 5: Assign Event IDs after merging
cluster_map = {}
event_counter = 1

template_to_event = {}

for i, template in enumerate(unique_templates):
    root = find(i)
    
    if root not in cluster_map:
        cluster_map[root] = f"E{event_counter:04d}"
        event_counter += 1
    
    template_to_event[template] = cluster_map[root]

# Step 6: Map back to dataframe
df["event_id"] = df["template"].map(template_to_event)

print("Total unique Event IDs after semantic merge:", len(set(template_to_event.values())))

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Batches:   0%|          | 0/86 [00:00<?, ?it/s]

Total unique Event IDs after semantic merge: 99

In [58]:
df_final = df[["event_id", "raw_log", "normalized_log", "template"]]

pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None)

print("\nFirst 50 structured logs:")
display(df_final.head(50))

print("\nLast 50 structured logs:")
display(df_final.tail(50))

First 50 structured logs:

,event_id,raw_log,normalized_log,template
0,E0001,mar 15 06:00:03 prod-app-01 api-gateway[3330]: <info> health check passed upstream=auth-service,mar <NUM> <TIME> prod-app-<NUM> api-gateway[<NUM>]: <info> health check passed upstream=auth-service,mar <NUM> <TIME> prod-app-<NUM> api-gateway[<NUM>]: <info> health check passed upstream=auth-service
1,E0002,2026-03-15 06:00:03 info [api-gateway] request completed method=get path=/api/v2/users/3591 status=200 duration=264ms,<NUM>-<NUM>-<NUM> <TIME> info [api-gateway] request completed method=get path=<PATH> status=<NUM> duration=264ms,<NUM>-<NUM>-<NUM> <TIME> info [api-gateway] request completed method=get path=<PATH> status=<NUM> duration=264ms
2,E0003,2026-03-15 06:00:07 warn [inventory] sync delay from erp: last update 47 minutes ago,<NUM>-<NUM>-<NUM> <TIME> warn [inventory] sync delay from erp: last update <NUM> minutes ago,<NUM>-<NUM>-<NUM> <TIME> warn [inventory] sync delay from erp: last update <NUM> minutes ago
3,E0004,2026-03-15 06:00:09 info [inventory] stock updated sku=gw-7547 qty=328 warehouse=wh-03,<NUM>-<NUM>-<NUM> <TIME> info [inventory] stock updated sku=gw-<NUM> qty=<NUM> warehouse=wh-<NUM>,<NUM>-<NUM>-<NUM> <TIME> info [inventory] stock updated sku=gw-<NUM> qty=<NUM> warehouse=wh-<NUM>
4,E0005,2026-03-15t06:00:11.927231z error auth-service: mfa verification failed uid=2160 code=invalid,<NUM>-<NUM>-15t06:<NUM>:<NUM>.927231z error auth-service: mfa verification failed uid=<NUM> code=invalid,<NUM>-<NUM>-15t06:<NUM>:<NUM>.927231z error auth-service: mfa verification failed uid=<NUM> code=invalid
5,E0002,2026-03-15 06:00:14 warn [api-gateway] request slow method=get path=/api/v2/search status=200 duration=2021ms,<NUM>-<NUM>-<NUM> <TIME> warn [api-gateway] request slow method=get path=<PATH> status=<NUM> duration=2021ms,<NUM>-<NUM>-<NUM> <TIME> warn [api-gateway] request slow method=get path=<PATH> status=<NUM> duration=2021ms
6,E0006,[06:00:17] i/auth-service: password reset requested uid=9085,[<TIME>] i<PATH> password reset requested uid=<NUM>,[<TIME>] i<PATH> password reset requested uid=<NUM>
7,E0003,mar 15 06:00:21 prod-app-01 inventory[4727]: <info> inventory sync completed source=erp records=2847 duration=12.4s,mar <NUM> <TIME> prod-app-<NUM> inventory[<NUM>]: <info> inventory sync completed source=erp records=<NUM> duration=<NUM>.4s,mar <NUM> <TIME> prod-app-<NUM> inventory[<NUM>]: <info> inventory sync completed source=erp records=<NUM> duration=<NUM>.4s
8,E0007,[06:00:25] i/email-service: email sent to=user677@company.io template=welcome msg_id=msg-739098,[<TIME>] i<PATH> email sent to=user677@company.io template=welcome msg_id=msg-<NUM>,[<TIME>] i<PATH> email sent to=user677@company.io template=welcome msg_id=msg-<NUM>
9,E0008,[06:00:28] i/api-gateway: request completed method=get path=/api/v2/products status=200 duration=49ms,[<TIME>] i<PATH> request completed method=get path=<PATH> status=<NUM> duration=49ms,[<TIME>] i<PATH> request completed method=get path=<PATH> status=<NUM> duration=49ms
10,E0009,"{""ts"": ""2026-03-15t06:00:29.047373z"", ""level"": ""info"", ""svc"": ""api-gateway"", ""msg"": ""health check passed upstream=inventory""}","{""ts"": ""<NUM>-<NUM>-15t06:<NUM>:<NUM>.047373z"", ""level"": ""info"", ""svc"": ""api-gateway"", ""msg"": ""health check passed upstream=inventory""}","{""ts"": ""<NUM>-<NUM>-15t06:<NUM>:<NUM>.047373z"", ""level"": ""info"", ""svc"": ""api-gateway"", ""msg"": ""health check passed upstream=inventory""}"
11,E0010,2026-03-15 06:00:33 info [payment-svc] payment method added uid=9834 type=card last4=6352,<NUM>-<NUM>-<NUM> <TIME> info [payment-svc] payment method added uid=<NUM> type=card last4=<NUM>,<NUM>-<NUM>-<NUM> <TIME> info [payment-svc] payment method added uid=<NUM> type=card last4=<NUM>
12,E0011,2026-03-15 06:00:37 info [inventory] shipment received shipment_id=shp-58689 items=48,<NUM>-<NUM>-<NUM> <TIME> info [inventory] shipment received shipment_id=shp-<NUM> items=<NUM>,<NUM>-<NUM>-<NUM> <TIME> info [inventory] shipment received shipment_id=shp-<NUM> items=<NUM>
13,E0012,"{""ts"": ""2026-03-15t06:00:37.842791z"", ""level"": ""info"", ""svc"": ""auth-service"", ""msg"": ""user logout uid=1514""}","{""ts"": ""<NUM>-<NUM>-15t06:<NUM>:<NUM>.842791z"", ""level"": ""info"", ""svc"": ""auth-service"", ""msg"": ""user logout uid=<NUM>""}","{""ts"": ""<NUM>-<NUM>-15t06:<NUM>:<NUM>.842791z"", ""level"": ""info"", ""svc"": ""auth-service"", ""msg"": ""user logout uid=<NUM>""}"
14,E0013,2026-03-15 06:00:40 info [inventory] reorder triggered sku=dx-8478 qty_ordered=500,<NUM>-<NUM>-<NUM> <TIME> info [inventory] reorder triggered sku=dx-<NUM> qty_ordered=<NUM>,<NUM>-<NUM>-<NUM> <TIME> info [inventory] reorder triggered sku=dx-<NUM> qty_ordered=<NUM>
15,E0014,2026-03-15 06:00:44 warn [scheduler] cron job slow job=daily_report_generation duration=145.3s threshold=60s,<NUM>-<NUM>-<NUM> <TIME> warn [scheduler] cron job slow job=daily_report_generation duration=<NUM>.3s threshold=60s,<NUM>-<NUM>-<NUM> <TIME> warn [scheduler] cron job slow job=daily_report_generation duration=<NUM>.3s threshold=60s
16,E0005,2026-03-15 06:00:48 warn [auth-service] session nearing expiry uid=4527 remaining=120s,<NUM>-<NUM>-<NUM> <TIME> warn [auth-service] session nearing expiry uid=<NUM> remaining=120s,<NUM>-<NUM>-<NUM> <TIME> warn [auth-service] session nearing expiry uid=<NUM> remaining=120s
17,E0007,[06:00:50] i/email-service: email sent to=user255@company.io template=order_confirmation msg_id=msg-219971,[<TIME>] i<PATH> email sent to=user255@company.io template=order_confirmation msg_id=msg-<NUM>,[<TIME>] i<PATH> email sent to=user255@company.io template=order_confirmation msg_id=msg-<NUM>
18,E0009,"{""ts"": ""2026-03-15t06:00:53.761702z"", ""level"": ""info"", ""svc"": ""api-gateway"", ""msg"": ""request completed method=get path=/api/v2/products status=200 duration=142ms""}","{""ts"": ""<NUM>-<NUM>-15t06:<NUM>:<NUM>.761702z"", ""level"": ""info"", ""svc"": ""api-gateway"", ""msg"": ""request completed method=get path=<PATH> status=<NUM> duration=142ms""}","{""ts"": ""<NUM>-<NUM>-15t06:<NUM>:<NUM>.761702z"", ""level"": ""info"", ""svc"": ""api-gateway"", ""msg"": ""request completed method=get path=<PATH> status=<NUM> duration=142ms""}"
19,E0005,mar 15 06:00:56 prod-web-01 auth-service[5564]: <info> mfa verification passed uid=7669,mar <NUM> <TIME> prod-web-<NUM> auth-service[<NUM>]: <info> mfa verification passed uid=<NUM>,mar <NUM> <TIME> prod-web-<NUM> auth-service[<NUM>]: <info> mfa verification passed uid=<NUM>
20,E0015,"{""ts"": ""2026-03-15t06:00:59.501009z"", ""level"": ""info"", ""svc"": ""inventory"", ""msg"": ""stock updated sku=cw-9702 qty=45 warehouse=wh-03"", ""trace_id"": ""trace-540226""}","{""ts"": ""<NUM>-<NUM>-15t06:<NUM>:<NUM>.501009z"", ""level"": ""info"", ""svc"": ""inventory"", ""msg"": ""stock updated sku=cw-<NUM> qty=<NUM> warehouse=wh-<NUM>"", ""trace_id"": ""trace-<NUM>""}","{""ts"": ""<NUM>-<NUM>-15t06:<NUM>:<NUM>.501009z"", ""level"": ""info"", ""svc"": ""inventory"", ""msg"": ""stock updated sku=cw-<NUM> qty=<NUM> warehouse=wh-<NUM>"", ""trace_id"": ""trace-<NUM>""}"
21,E0007,2026-03-15 06:01:01 info [email-service] email sent to=user558@gmail.com template=order_confirmation msg_id=msg-216276,<NUM>-<NUM>-<NUM> <TIME> info [email-service] email sent to=user558@gmail.com template=order_confirmation msg_id=msg-<NUM>,<NUM>-<NUM>-<NUM> <TIME> info [email-service] email sent to=user558@gmail.com template=order_confirmation msg_id=msg-<NUM>
22,E0016,[06:01:05] i/payment-svc: payment processed order_id=ord-321494 amount=385.99 currency=usd,[<TIME>] i<PATH> payment processed order_id=ord-<NUM> amount=<NUM>.<NUM> currency=usd,[<TIME>] i<PATH> payment processed order_id=ord-<NUM> amount=<NUM>.<NUM> currency=usd
23,E0017,2026-03-15t06:01:09.298837z error auth-service: ldap connection refused host=ldap-primary.internal:389,<NUM>-<NUM>-15t06:<NUM>:<NUM>.298837z error auth-service: ldap connection refused host=ldap-primary.internal:<NUM>,<NUM>-<NUM>-15t06:<NUM>:<NUM>.298837z error auth-service: ldap connection refused host=ldap-primary.internal:<NUM>
24,E0005,mar 15 06:01:11 prod-db-01 auth-service[8354]: <warn> login attempt with expired token uid=3504,mar <NUM> <TIME> prod-db-<NUM> auth-service[<NUM>]: <warn> login attempt with expired token uid=<NUM>,mar <NUM> <TIME> prod-db-<NUM> auth-service[<NUM>]: <warn> login attempt with expired token uid=<NUM>
25,E0018,mar 15 06:01:14 prod-web-01 payment-svc[9307]: <error> payment gateway returned http 503 endpoint=api.stripe.internal/v1/charges,mar <NUM> <TIME> prod-web-<NUM> payment-svc[<NUM>]: <error> payment gateway returned http <NUM> endpoint=api.stripe.internal<PATH>,mar <NUM> <TIME> prod-web-<NUM> payment-svc[<NUM>]: <error> payment gateway returned http <NUM> endpoint=api.stripe.internal<PATH>
26,E0005,mar 15 06:01:16 prod-web-02 auth-service[6962]: <error> mfa verification failed uid=4483 code=invalid,mar <NUM> <TIME> prod-web-<NUM> auth-service[<NUM>]: <error> mfa verification failed uid=<NUM> code=invalid,mar <NUM> <TIME> prod-web-<NUM> auth-service[<NUM>]: <error> mfa verification failed uid=<NUM> code=invalid
27,E0019,2026-03-15t06:01:18.709534z warn api-gateway: upstream timeout upstream=inventory duration=5000ms,<NUM>-<NUM>-15t06:<NUM>:<NUM>.709534z warn api-gateway: upstream timeout upstream=inventory duration=5000ms,<NUM>-<NUM>-15t06:<NUM>:<NUM>.709534z warn api-gateway: upstream timeout upstream=inventory duration=5000ms
28,E0003,2026-03-15 06:01:21 warn [inventory] sync delay from erp: last update 47 minutes ago,<NUM>-<NUM>-<NUM> <TIME> warn [inventory] sync delay from erp: last update <NUM> minutes ago,<NUM>-<NUM>-<NUM> <TIME> warn [inventory] sync delay from erp: last update <NUM> minutes ago
29,E0020,"{""ts"": ""2026-03-15t06:01:25.962935z"", ""level"": ""info"", ""svc"": ""email-service"", ""msg"": ""email sent to=user430@company.io template=welcome msg_id=msg-888939""}","{""ts"": ""<NUM>-<NUM>-15t06:<NUM>:<NUM>.962935z"", ""level"": ""info"", ""svc"": ""email-service"", ""msg"": ""email sent to=user430@company.io template=welcome msg_id=msg-<NUM>""}","{""ts"": ""<NUM>-<NUM>-15t06:<NUM>:<NUM>.962935z"", ""level"": ""info"", ""svc"": ""email-service"", ""msg"": ""email sent to=user430@company.io template=welcome msg_id=msg-<NUM>""}"
30,E0011,mar 15 06:01:28 prod-web-01 inventory[5670]: <info> shipment received shipment_id=shp-23446 items=48,mar <NUM> <TIME> prod-web-<NUM> inventory[<NUM>]: <info> shipment received shipment_id=shp-<NUM> items=<NUM>,mar <NUM> <TIME> prod-web-<NUM> inventory[<NUM>]: <info> shipment received shipment_id=shp-<NUM> items=<NUM>
31,E0003,2026-03-15 06:01:29 info [inventory] inventory sync completed source=erp records=2847 duration=12.4s,<NUM>-<NUM>-<NUM> <TIME> info [inventory] inventory sync completed source=erp records=<NUM> duration=<NUM>.4s,<NUM>-<NUM>-<NUM> <TIME> info [inventory] inventory sync completed source=erp records=<NUM> duration=<NUM>.4s
32,E0004,2026-03-15 06:01:29 info [inventory] stock updated sku=cx-7267 qty=34 warehouse=wh-02,<NUM>-<NUM>-<NUM> <TIME> info [inventory] stock updated sku=cx-<NUM> qty=<NUM> warehouse=wh-<NUM>,<NUM>-<NUM>-<NUM> <TIME> info [inventory] stock updated sku=cx-<NUM> qty=<NUM> warehouse=wh-<NUM>
33,E0002,2026-03-15 06:01:33 warn [api-gateway] rate limit exceeded client_id=app-657 limit=1000/min,<NUM>-<NUM>-<NUM> <TIME> warn [api-gateway] rate limit exceeded client_id=app-<NUM> limit=<NUM><PATH>,<NUM>-<NUM>-<NUM> <TIME> warn [api-gateway] rate limit exceeded client_id=app-<NUM> limit=<NUM><PATH>
34,E0005,[06:01:35] i/auth-service: mfa verification passed uid=6107,[<TIME>] i<PATH> mfa verification passed uid=<NUM>,[<TIME>] i<PATH> mfa verification passed uid=<NUM>
35,E0021,[06:01:36] i/auth-service: user login successful uid=4456,[<TIME>] i<PATH> user login successful uid=<NUM>,[<TIME>] i<PATH> user login successful uid=<NUM>
36,E0001,2026-03-15t06:01:39.825153z info api-gateway: health check passed upstream=payment-svc,<NUM>-<NUM>-15t06:<NUM>:<NUM>.825153z info api-gateway: health check passed upstream=payment-svc,<NUM>-<NUM>-15t06:<NUM>:<NUM>.825153z info api-gateway: health check passed upstream=payment-svc
37,E0009,"{""ts"": ""2026-03-15t06:01:42.116088z"", ""level"": ""info"", ""svc"": ""api-gateway"", ""msg"": ""request completed method=get path=/api/v2/users/7873 status=200 duration=236ms""}","{""ts"": ""<NUM>-<NUM>-15t06:<NUM>:<NUM>.116088z"", ""level"": ""info"", ""svc"": ""api-gateway"", ""msg"": ""request completed method=get path=<PATH> status=<NUM> duration=236ms""}","{""ts"": ""<NUM>-<NUM>-15t06:<NUM>:<NUM>.116088z"", ""level"": ""info"", ""svc"": ""api-gateway"", ""msg"": ""request completed method=get path=<PATH> status=<NUM> duration=236ms""}"
38,E0022,2026-03-15 06:01:44 info [payment-svc] refund initiated order_id=ord-871411 amount=101.15,<NUM>-<NUM>-<NUM> <TIME> info [payment-svc] refund initiated order_id=ord-<NUM> amount=<NUM>.<NUM>,<NUM>-<NUM>-<NUM> <TIME> info [payment-svc] refund initiated order_id=ord-<NUM> amount=<NUM>.<NUM>
39,E0023,"{""ts"": ""2026-03-15t06:01:44.501809z"", ""level"": ""error"", ""svc"": ""inventory"", ""msg"": ""warehouse api unreachable warehouse=wh-03 error=econnrefused"", ""trace_id"": ""trace-618019""}","{""ts"": ""<NUM>-<NUM>-15t06:<NUM>:<NUM>.501809z"", ""level"": ""error"", ""svc"": ""inventory"", ""msg"": ""warehouse api unreachable warehouse=wh-<NUM> error=econnrefused"", ""trace_id"": ""trace-<NUM>""}","{""ts"": ""<NUM>-<NUM>-15t06:<NUM>:<NUM>.501809z"", ""level"": ""error"", ""svc"": ""inventory"", ""msg"": ""warehouse api unreachable warehouse=wh-<NUM> error=econnrefused"", ""trace_id"": ""trace-<NUM>""}"
40,E0008,[06:01:44] i/api-gateway: request completed method=get path=/api/v2/users/1434 status=200 duration=221ms,[<TIME>] i<PATH> request completed method=get path=<PATH> status=<NUM> duration=221ms,[<TIME>] i<PATH> request completed method=get path=<PATH> status=<NUM> duration=221ms
41,E0002,"mar 15 06:01:48 prod-web-01 api-gateway[9234]: <error> request failed method=post path=/api/v2/checkout status=500 duration=189ms error=""internal server error""","mar <NUM> <TIME> prod-web-<NUM> api-gateway[<NUM>]: <error> request failed method=post path=<PATH> status=<NUM> duration=189ms error=""internal server error""","mar <NUM> <TIME> prod-web-<NUM> api-gateway[<NUM>]: <error> request failed method=post path=<PATH> status=<NUM> duration=189ms error=""internal server error"""
42,E0024,mar 15 06:01:51 prod-app-01 api-gateway[8912]: <error> tls handshake failed client_ip=192.168.2.64 error=certificate_expired,mar <NUM> <TIME> prod-app-<NUM> api-gateway[<NUM>]: <error> tls handshake failed client_ip=<IP> error=certificate_expired,mar <NUM> <TIME> prod-app-<NUM> api-gateway[<NUM>]: <error> tls handshake failed client_ip=<IP> error=certificate_expired
43,E0001,2026-03-15 06:01:53 info [api-gateway] health check passed upstream=auth-service,<NUM>-<NUM>-<NUM> <TIME> info [api-gateway] health check passed upstream=auth-service,<NUM>-<NUM>-<NUM> <TIME> info [api-gateway] health check passed upstream=auth-service
44,E0002,mar 15 06:01:54 prod-web-01 api-gateway[1828]: <info> request completed method=post path=/api/v2/orders status=201 duration=251ms,mar <NUM> <TIME> prod-web-<NUM> api-gateway[<NUM>]: <info> request completed method=post path=<PATH> status=<NUM> duration=251ms,mar <NUM> <TIME> prod-web-<NUM> api-gateway[<NUM>]: <info> request completed method=post path=<PATH> status=<NUM> duration=251ms
45,E0025,"{""ts"": ""2026-03-15t06:01:55.988078z"", ""level"": ""info"", ""svc"": ""payment-svc"", ""msg"": ""payment processed order_id=ord-377319 amount=366.47 currency=usd"", ""trace_id"": ""trace-753516""}","{""ts"": ""<NUM>-<NUM>-15t06:<NUM>:<NUM>.988078z"", ""level"": ""info"", ""svc"": ""payment-svc"", ""msg"": ""payment processed order_id=ord-<NUM> amount=<NUM>.<NUM> currency=usd"", ""trace_id"": ""trace-<NUM>""}","{""ts"": ""<NUM>-<NUM>-15t06:<NUM>:<NUM>.988078z"", ""level"": ""info"", ""svc"": ""payment-svc"", ""msg"": ""payment processed order_id=ord-<NUM> amount=<NUM>.<NUM> currency=usd"", ""trace_id"": ""trace-<NUM>""}"
46,E0013,2026-03-15 06:01:59 info [inventory] reorder triggered sku=cy-7275 qty_ordered=500,<NUM>-<NUM>-<NUM> <TIME> info [inventory] reorder triggered sku=cy-<NUM> qty_ordered=<NUM>,<NUM>-<NUM>-<NUM> <TIME> info [inventory] reorder triggered sku=cy-<NUM> qty_ordered=<NUM>
47,E0026,mar 15 06:02:02 prod-web-01 payment-svc[8871]: <info> invoice generated invoice_id=inv-20266036,mar <NUM> <TIME> prod-web-<NUM> payment-svc[<NUM>]: <info> invoice generated invoice_id=inv-<NUM>,mar <NUM> <TIME> prod-web-<NUM> payment-svc[<NUM>]: <info> invoice generated invoice_id=inv-<NUM>
48,E0005,mar 15 06:02:03 prod-app-01 auth-service[8837]: <info> user login successful uid=2403,mar <NUM> <TIME> prod-app-<NUM> auth-service[<NUM>]: <info> user login successful uid=<NUM>,mar <NUM> <TIME> prod-app-<NUM> auth-service[<NUM>]: <info> user login successful uid=<NUM>
49,E0010,2026-03-15 06:02:06 info [payment-svc] payment method added uid=7932 type=card last4=5571,<NUM>-<NUM>-<NUM> <TIME> info [payment-svc] payment method added uid=<NUM> type=card last4=<NUM>,<NUM>-<NUM>-<NUM> <TIME> info [payment-svc] payment method added uid=<NUM> type=card last4=<NUM>

Last 50 structured logs:

,event_id,raw_log,normalized_log,template
5145,E0002,2026-03-15t08:54:41.945573z info api-gateway: request completed method=get path=/api/v2/users/3621 status=200 duration=33ms,<NUM>-<NUM>-15t08:<NUM>:<NUM>.945573z info api-gateway: request completed method=get path=<PATH> status=<NUM> duration=33ms,<NUM>-<NUM>-15t08:<NUM>:<NUM>.945573z info api-gateway: request completed method=get path=<PATH> status=<NUM> duration=33ms
5146,E0058,"{""ts"": ""2026-03-15t08:54:45.696086z"", ""level"": ""info"", ""svc"": ""payment-svc"", ""msg"": ""invoice generated invoice_id=inv-20266194""}","{""ts"": ""<NUM>-<NUM>-15t08:<NUM>:<NUM>.696086z"", ""level"": ""info"", ""svc"": ""payment-svc"", ""msg"": ""invoice generated invoice_id=inv-<NUM>""}","{""ts"": ""<NUM>-<NUM>-15t08:<NUM>:<NUM>.696086z"", ""level"": ""info"", ""svc"": ""payment-svc"", ""msg"": ""invoice generated invoice_id=inv-<NUM>""}"
5147,E0012,"{""ts"": ""2026-03-15t08:54:46.228665z"", ""level"": ""info"", ""svc"": ""auth-service"", ""msg"": ""mfa verification passed uid=8962""}","{""ts"": ""<NUM>-<NUM>-15t08:<NUM>:<NUM>.228665z"", ""level"": ""info"", ""svc"": ""auth-service"", ""msg"": ""mfa verification passed uid=<NUM>""}","{""ts"": ""<NUM>-<NUM>-15t08:<NUM>:<NUM>.228665z"", ""level"": ""info"", ""svc"": ""auth-service"", ""msg"": ""mfa verification passed uid=<NUM>""}"
5148,E0026,mar 15 08:54:49 prod-app-01 payment-svc[3749]: <info> invoice generated invoice_id=inv-20264112,mar <NUM> <TIME> prod-app-<NUM> payment-svc[<NUM>]: <info> invoice generated invoice_id=inv-<NUM>,mar <NUM> <TIME> prod-app-<NUM> payment-svc[<NUM>]: <info> invoice generated invoice_id=inv-<NUM>
5149,E0044,mar 15 08:54:50 prod-web-01 auth-service[9287]: <warn> rate limit approaching for ip 10.0.1.130,mar <NUM> <TIME> prod-web-<NUM> auth-service[<NUM>]: <warn> rate limit approaching for ip <IP>,mar <NUM> <TIME> prod-web-<NUM> auth-service[<NUM>]: <warn> rate limit approaching for ip <IP>
5150,E0019,2026-03-15 08:54:52 warn [api-gateway] upstream timeout upstream=inventory duration=5000ms,<NUM>-<NUM>-<NUM> <TIME> warn [api-gateway] upstream timeout upstream=inventory duration=5000ms,<NUM>-<NUM>-<NUM> <TIME> warn [api-gateway] upstream timeout upstream=inventory duration=5000ms
5151,E0003,2026-03-15 08:54:57 info [inventory] inventory sync completed source=erp records=2847 duration=12.4s,<NUM>-<NUM>-<NUM> <TIME> info [inventory] inventory sync completed source=erp records=<NUM> duration=<NUM>.4s,<NUM>-<NUM>-<NUM> <TIME> info [inventory] inventory sync completed source=erp records=<NUM> duration=<NUM>.4s
5152,E0005,2026-03-15 08:55:00 info [auth-service] user login successful uid=1916,<NUM>-<NUM>-<NUM> <TIME> info [auth-service] user login successful uid=<NUM>,<NUM>-<NUM>-<NUM> <TIME> info [auth-service] user login successful uid=<NUM>
5153,E0002,mar 15 08:55:02 prod-web-01 api-gateway[7557]: <warn> rate limit exceeded client_id=app-908 limit=1000/min,mar <NUM> <TIME> prod-web-<NUM> api-gateway[<NUM>]: <warn> rate limit exceeded client_id=app-<NUM> limit=<NUM><PATH>,mar <NUM> <TIME> prod-web-<NUM> api-gateway[<NUM>]: <warn> rate limit exceeded client_id=app-<NUM> limit=<NUM><PATH>
5154,E0005,15/mar/2026:08:55:02 +0530 | warn | auth-service | login attempt with expired token uid=8744,<NUM><PATH> +<NUM> | warn | auth-service | login attempt with expired token uid=<NUM>,<NUM><PATH> +<NUM> | warn | auth-service | login attempt with expired token uid=<NUM>
5155,E0046,[08:55:06] i/api-gateway: health check passed upstream=inventory,[<TIME>] i<PATH> health check passed upstream=inventory,[<TIME>] i<PATH> health check passed upstream=inventory
5156,E0061,"mar 15 08:55:09 prod-web-01 scheduler[2440]: <error> scheduler heartbeat missed, possible zombie process pid=28441","mar <NUM> <TIME> prod-web-<NUM> scheduler[<NUM>]: <error> scheduler heartbeat missed, possible zombie process pid=<NUM>","mar <NUM> <TIME> prod-web-<NUM> scheduler[<NUM>]: <error> scheduler heartbeat missed, possible zombie process pid=<NUM>"
5157,E0001,mar 15 08:55:12 prod-web-01 api-gateway[9171]: <info> health check passed upstream=payment-svc,mar <NUM> <TIME> prod-web-<NUM> api-gateway[<NUM>]: <info> health check passed upstream=payment-svc,mar <NUM> <TIME> prod-web-<NUM> api-gateway[<NUM>]: <info> health check passed upstream=payment-svc
5158,E0014,[08:55:15] i/scheduler: cron job executed job=daily_report_generation duration=18.7s,[<TIME>] i<PATH> cron job executed job=daily_report_generation duration=<NUM>.7s,[<TIME>] i<PATH> cron job executed job=daily_report_generation duration=<NUM>.7s
5159,E0008,[08:55:16] i/api-gateway: request completed method=get path=/api/v2/users/2403 status=200 duration=29ms,[<TIME>] i<PATH> request completed method=get path=<PATH> status=<NUM> duration=29ms,[<TIME>] i<PATH> request completed method=get path=<PATH> status=<NUM> duration=29ms
5160,E0001,[08:55:17] i/api-gateway: health check passed upstream=auth-service,[<TIME>] i<PATH> health check passed upstream=auth-service,[<TIME>] i<PATH> health check passed upstream=auth-service
5161,E0014,2026-03-15 08:55:17 info [scheduler] cron job executed job=cache_warmup duration=5.1s keys=12847,<NUM>-<NUM>-<NUM> <TIME> info [scheduler] cron job executed job=cache_warmup duration=<NUM>.1s keys=<NUM>,<NUM>-<NUM>-<NUM> <TIME> info [scheduler] cron job executed job=cache_warmup duration=<NUM>.1s keys=<NUM>
5162,E0043,2026-03-15 08:55:18 error [email-service] template rendering failed template=invoice_v2 error=missing variable 'company_name',<NUM>-<NUM>-<NUM> <TIME> error [email-service] template rendering failed template=invoice_v2 error=missing variable 'company_name',<NUM>-<NUM>-<NUM> <TIME> error [email-service] template rendering failed template=invoice_v2 error=missing variable 'company_name'
5163,E0004,2026-03-15t08:55:18.941907z info inventory: stock updated sku=gw-7547 qty=304 warehouse=wh-03,<NUM>-<NUM>-15t08:<NUM>:<NUM>.941907z info inventory: stock updated sku=gw-<NUM> qty=<NUM> warehouse=wh-<NUM>,<NUM>-<NUM>-15t08:<NUM>:<NUM>.941907z info inventory: stock updated sku=gw-<NUM> qty=<NUM> warehouse=wh-<NUM>
5164,E0002,2026-03-15t08:55:20.667570z warn api-gateway: request slow method=get path=/api/v2/search status=200 duration=4037ms,<NUM>-<NUM>-15t08:<NUM>:<NUM>.667570z warn api-gateway: request slow method=get path=<PATH> status=<NUM> duration=4037ms,<NUM>-<NUM>-15t08:<NUM>:<NUM>.667570z warn api-gateway: request slow method=get path=<PATH> status=<NUM> duration=4037ms
5165,E0093,/app/src/worker/batch.go:142 +0x3a7,<PATH> +0x3a7,<PATH> +0x3a7
5166,E0057,2026-03-15 08:55:29 warn [email-service] bounce detected to=user576@outlook.com type=soft reason=mailbox_full,<NUM>-<NUM>-<NUM> <TIME> warn [email-service] bounce detected to=user576@outlook.com type=soft reason=mailbox_full,<NUM>-<NUM>-<NUM> <TIME> warn [email-service] bounce detected to=user576@outlook.com type=soft reason=mailbox_full
5167,E0008,[08:55:30] i/api-gateway: request completed method=get path=/api/v2/products status=200 duration=132ms,[<TIME>] i<PATH> request completed method=get path=<PATH> status=<NUM> duration=132ms,[<TIME>] i<PATH> request completed method=get path=<PATH> status=<NUM> duration=132ms
5168,E0007,2026-03-15 08:55:31 info [email-service] email sent to=user687@outlook.com template=welcome msg_id=msg-610120,<NUM>-<NUM>-<NUM> <TIME> info [email-service] email sent to=user687@outlook.com template=welcome msg_id=msg-<NUM>,<NUM>-<NUM>-<NUM> <TIME> info [email-service] email sent to=user687@outlook.com template=welcome msg_id=msg-<NUM>
5169,E0009,"{""ts"": ""2026-03-15t08:55:34.530237z"", ""level"": ""info"", ""svc"": ""api-gateway"", ""msg"": ""request completed method=get path=/api/v2/products status=200 duration=80ms""}","{""ts"": ""<NUM>-<NUM>-15t08:<NUM>:<NUM>.530237z"", ""level"": ""info"", ""svc"": ""api-gateway"", ""msg"": ""request completed method=get path=<PATH> status=<NUM> duration=80ms""}","{""ts"": ""<NUM>-<NUM>-15t08:<NUM>:<NUM>.530237z"", ""level"": ""info"", ""svc"": ""api-gateway"", ""msg"": ""request completed method=get path=<PATH> status=<NUM> duration=80ms""}"
5170,E0009,"{""ts"": ""2026-03-15t08:55:37.223411z"", ""level"": ""info"", ""svc"": ""api-gateway"", ""msg"": ""health check passed upstream=auth-service"", ""trace_id"": ""trace-285236""}","{""ts"": ""<NUM>-<NUM>-15t08:<NUM>:<NUM>.223411z"", ""level"": ""info"", ""svc"": ""api-gateway"", ""msg"": ""health check passed upstream=auth-service"", ""trace_id"": ""trace-<NUM>""}","{""ts"": ""<NUM>-<NUM>-15t08:<NUM>:<NUM>.223411z"", ""level"": ""info"", ""svc"": ""api-gateway"", ""msg"": ""health check passed upstream=auth-service"", ""trace_id"": ""trace-<NUM>""}"
5171,E0014,15/mar/2026:08:55:40 +0530 | warn | scheduler | cron job slow job=daily_report_generation duration=145.3s threshold=60s,<NUM><PATH> +<NUM> | warn | scheduler | cron job slow job=daily_report_generation duration=<NUM>.3s threshold=60s,<NUM><PATH> +<NUM> | warn | scheduler | cron job slow job=daily_report_generation duration=<NUM>.3s threshold=60s
5172,E0010,2026-03-15 08:55:40 info [payment-svc] payment method added uid=3927 type=card last4=5056,<NUM>-<NUM>-<NUM> <TIME> info [payment-svc] payment method added uid=<NUM> type=card last4=<NUM>,<NUM>-<NUM>-<NUM> <TIME> info [payment-svc] payment method added uid=<NUM> type=card last4=<NUM>
5173,E0001,15/mar/2026:08:55:41 +0530 | info | api-gateway | health check passed upstream=inventory,<NUM><PATH> +<NUM> | info | api-gateway | health check passed upstream=inventory,<NUM><PATH> +<NUM> | info | api-gateway | health check passed upstream=inventory
5174,E0015,"{""ts"": ""2026-03-15t08:55:42.584852z"", ""level"": ""warn"", ""svc"": ""inventory"", ""msg"": ""sync delay from erp: last update 47 minutes ago"", ""trace_id"": ""trace-530310""}","{""ts"": ""<NUM>-<NUM>-15t08:<NUM>:<NUM>.584852z"", ""level"": ""warn"", ""svc"": ""inventory"", ""msg"": ""sync delay from erp: last update <NUM> minutes ago"", ""trace_id"": ""trace-<NUM>""}","{""ts"": ""<NUM>-<NUM>-15t08:<NUM>:<NUM>.584852z"", ""level"": ""warn"", ""svc"": ""inventory"", ""msg"": ""sync delay from erp: last update <NUM> minutes ago"", ""trace_id"": ""trace-<NUM>""}"
5175,E0008,[08:55:46] i/api-gateway: request completed method=get path=/api/v2/users/4593 status=200 duration=80ms,[<TIME>] i<PATH> request completed method=get path=<PATH> status=<NUM> duration=80ms,[<TIME>] i<PATH> request completed method=get path=<PATH> status=<NUM> duration=80ms
5176,E0036,"15/mar/2026:08:55:47 +0530 | warn | payment-svc | currency conversion rate stale, using cached value","<NUM><PATH> +<NUM> | warn | payment-svc | currency conversion rate stale, using cached value","<NUM><PATH> +<NUM> | warn | payment-svc | currency conversion rate stale, using cached value"
5177,E0026,mar 15 08:55:50 prod-app-01 payment-svc[7018]: <info> invoice generated invoice_id=inv-20264006,mar <NUM> <TIME> prod-app-<NUM> payment-svc[<NUM>]: <info> invoice generated invoice_id=inv-<NUM>,mar <NUM> <TIME> prod-app-<NUM> payment-svc[<NUM>]: <info> invoice generated invoice_id=inv-<NUM>
5178,E0085,"[08:55:50] w/email-service: smtp connection pool exhausted, waiting for available connection","[<TIME>] w<PATH> smtp connection pool exhausted, waiting for available connection","[<TIME>] w<PATH> smtp connection pool exhausted, waiting for available connection"
5179,E0058,"{""ts"": ""2026-03-15t08:55:55.042835z"", ""level"": ""info"", ""svc"": ""payment-svc"", ""msg"": ""invoice generated invoice_id=inv-20263030""}","{""ts"": ""<NUM>-<NUM>-15t08:<NUM>:<NUM>.042835z"", ""level"": ""info"", ""svc"": ""payment-svc"", ""msg"": ""invoice generated invoice_id=inv-<NUM>""}","{""ts"": ""<NUM>-<NUM>-15t08:<NUM>:<NUM>.042835z"", ""level"": ""info"", ""svc"": ""payment-svc"", ""msg"": ""invoice generated invoice_id=inv-<NUM>""}"
5180,E0005,2026-03-15 08:55:57 info [auth-service] session created for uid=4598 ttl=3600,<NUM>-<NUM>-<NUM> <TIME> info [auth-service] session created for uid=<NUM> ttl=<NUM>,<NUM>-<NUM>-<NUM> <TIME> info [auth-service] session created for uid=<NUM> ttl=<NUM>
5181,E0008,[08:56:00] i/api-gateway: request completed method=get path=/api/v2/products status=200 duration=146ms,[<TIME>] i<PATH> request completed method=get path=<PATH> status=<NUM> duration=146ms,[<TIME>] i<PATH> request completed method=get path=<PATH> status=<NUM> duration=146ms
5182,E0022,2026-03-15 08:56:02 info [payment-svc] refund initiated order_id=ord-289740 amount=127.02,<NUM>-<NUM>-<NUM> <TIME> info [payment-svc] refund initiated order_id=ord-<NUM> amount=<NUM>.<NUM>,<NUM>-<NUM>-<NUM> <TIME> info [payment-svc] refund initiated order_id=ord-<NUM> amount=<NUM>.<NUM>
5183,E0009,"{""ts"": ""2026-03-15t08:56:05.483431z"", ""level"": ""info"", ""svc"": ""api-gateway"", ""msg"": ""health check passed upstream=inventory""}","{""ts"": ""<NUM>-<NUM>-15t08:<NUM>:<NUM>.483431z"", ""level"": ""info"", ""svc"": ""api-gateway"", ""msg"": ""health check passed upstream=inventory""}","{""ts"": ""<NUM>-<NUM>-15t08:<NUM>:<NUM>.483431z"", ""level"": ""info"", ""svc"": ""api-gateway"", ""msg"": ""health check passed upstream=inventory""}"
5184,E0047,2026-03-15 08:56:08 info [email-service] email queue drained: 0 pending,<NUM>-<NUM>-<NUM> <TIME> info [email-service] email queue drained: <NUM> pending,<NUM>-<NUM>-<NUM> <TIME> info [email-service] email queue drained: <NUM> pending
5185,E0047,2026-03-15 08:56:09 info [email-service] email queue drained: 0 pending,<NUM>-<NUM>-<NUM> <TIME> info [email-service] email queue drained: <NUM> pending,<NUM>-<NUM>-<NUM> <TIME> info [email-service] email queue drained: <NUM> pending
5186,E0014,mar 15 08:56:14 prod-web-02 scheduler[9935]: <info> cron job executed job=daily_report_generation duration=18.7s,mar <NUM> <TIME> prod-web-<NUM> scheduler[<NUM>]: <info> cron job executed job=daily_report_generation duration=<NUM>.7s,mar <NUM> <TIME> prod-web-<NUM> scheduler[<NUM>]: <info> cron job executed job=daily_report_generation duration=<NUM>.7s
5187,E0004,[08:56:15] i/inventory: stock updated sku=hx-5681 qty=18 warehouse=wh-02,[<TIME>] i<PATH> stock updated sku=hx-<NUM> qty=<NUM> warehouse=wh-<NUM>,[<TIME>] i<PATH> stock updated sku=hx-<NUM> qty=<NUM> warehouse=wh-<NUM>
5188,E0008,[08:56:19] i/api-gateway: request completed method=post path=/api/v2/orders status=201 duration=202ms,[<TIME>] i<PATH> request completed method=post path=<PATH> status=<NUM> duration=202ms,[<TIME>] i<PATH> request completed method=post path=<PATH> status=<NUM> duration=202ms
5189,E0057,2026-03-15 08:56:24 warn [email-service] bounce detected to=user419@example.org type=soft reason=mailbox_full,<NUM>-<NUM>-<NUM> <TIME> warn [email-service] bounce detected to=user419@example.org type=soft reason=mailbox_full,<NUM>-<NUM>-<NUM> <TIME> warn [email-service] bounce detected to=user419@example.org type=soft reason=mailbox_full
5190,E0020,"{""ts"": ""2026-03-15t08:56:27.161828z"", ""level"": ""info"", ""svc"": ""email-service"", ""msg"": ""email sent to=user867@gmail.com template=order_confirmation msg_id=msg-647972"", ""trace_id"": ""trace-245031""}","{""ts"": ""<NUM>-<NUM>-15t08:<NUM>:<NUM>.161828z"", ""level"": ""info"", ""svc"": ""email-service"", ""msg"": ""email sent to=user867@gmail.com template=order_confirmation msg_id=msg-<NUM>"", ""trace_id"": ""trace-<NUM>""}","{""ts"": ""<NUM>-<NUM>-15t08:<NUM>:<NUM>.161828z"", ""level"": ""info"", ""svc"": ""email-service"", ""msg"": ""email sent to=user867@gmail.com template=order_confirmation msg_id=msg-<NUM>"", ""trace_id"": ""trace-<NUM>""}"
5191,E0008,[08:56:29] i/api-gateway: request completed method=get path=/api/v2/users/8749 status=200 duration=105ms,[<TIME>] i<PATH> request completed method=get path=<PATH> status=<NUM> duration=105ms,[<TIME>] i<PATH> request completed method=get path=<PATH> status=<NUM> duration=105ms
5192,E0047,2026-03-15 08:56:32 info [email-service] email queue drained: 0 pending,<NUM>-<NUM>-<NUM> <TIME> info [email-service] email queue drained: <NUM> pending,<NUM>-<NUM>-<NUM> <TIME> info [email-service] email queue drained: <NUM> pending
5193,E0044,mar 15 08:56:34 prod-app-01 auth-service[3542]: <warn> rate limit approaching for ip 192.168.10.153,mar <NUM> <TIME> prod-app-<NUM> auth-service[<NUM>]: <warn> rate limit approaching for ip <IP>,mar <NUM> <TIME> prod-app-<NUM> auth-service[<NUM>]: <warn> rate limit approaching for ip <IP>
5194,E0002,2026-03-15t08:56:37.648949z info api-gateway: request completed method=get path=/api/v2/users/4510 status=200 duration=14ms,<NUM>-<NUM>-15t08:<NUM>:<NUM>.648949z info api-gateway: request completed method=get path=<PATH> status=<NUM> duration=14ms,<NUM>-<NUM>-15t08:<NUM>:<NUM>.648949z info api-gateway: request completed method=get path=<PATH> status=<NUM> duration=14ms

In [59]:
# Create event summary with template meaning
event_summary = df.groupby("event_id").agg({
    "template": "first",
    "event_id": "count"
}).rename(columns={"event_id": "count"}).reset_index()

total_event_ids = len(event_summary)

print("Total unique Event IDs:", total_event_ids)

print("\nTop Event IDs:")
display(event_summary.sort_values(by="count", ascending=False).head(100))

print(f"Total logs: {len(df)}")
print(f"Total unique Event IDs: {total_event_ids}")
print(f"Average logs per Event ID: {len(df) // total_event_ids}")

Total unique Event IDs: 99

Top Event IDs:

,event_id,template,count
4,E0005,<NUM>-<NUM>-15t06:<NUM>:<NUM>.927231z error auth-service: mfa verification failed uid=<NUM> code=invalid,710
1,E0002,<NUM>-<NUM>-<NUM> <TIME> info [api-gateway] request completed method=get path=<PATH> status=<NUM> duration=264ms,500
8,E0009,"{""ts"": ""<NUM>-<NUM>-15t06:<NUM>:<NUM>.047373z"", ""level"": ""info"", ""svc"": ""api-gateway"", ""msg"": ""health check passed upstream=inventory""}",311
0,E0001,mar <NUM> <TIME> prod-app-<NUM> api-gateway[<NUM>]: <info> health check passed upstream=auth-service,305
6,E0007,[<TIME>] i<PATH> email sent to=user677@company.io template=welcome msg_id=msg-<NUM>,192
13,E0014,<NUM>-<NUM>-<NUM> <TIME> warn [scheduler] cron job slow job=daily_report_generation duration=<NUM>.3s threshold=60s,144
2,E0003,<NUM>-<NUM>-<NUM> <TIME> warn [inventory] sync delay from erp: last update <NUM> minutes ago,134
11,E0012,"{""ts"": ""<NUM>-<NUM>-15t06:<NUM>:<NUM>.842791z"", ""level"": ""info"", ""svc"": ""auth-service"", ""msg"": ""user logout uid=<NUM>""}",131
14,E0015,"{""ts"": ""<NUM>-<NUM>-15t06:<NUM>:<NUM>.501009z"", ""level"": ""info"", ""svc"": ""inventory"", ""msg"": ""stock updated sku=cw-<NUM> qty=<NUM> warehouse=wh-<NUM>"", ""trace_id"": ""trace-<NUM>""}",131
3,E0004,<NUM>-<NUM>-<NUM> <TIME> info [inventory] stock updated sku=gw-<NUM> qty=<NUM> warehouse=wh-<NUM>,124
46,E0047,<NUM>-<NUM>-15t06:<NUM>:<NUM>.557127z info email-service: email queue drained: <NUM> pending,117
10,E0011,<NUM>-<NUM>-<NUM> <TIME> info [inventory] shipment received shipment_id=shp-<NUM> items=<NUM>,99
12,E0013,<NUM>-<NUM>-<NUM> <TIME> info [inventory] reorder triggered sku=dx-<NUM> qty_ordered=<NUM>,92
23,E0024,mar <NUM> <TIME> prod-app-<NUM> api-gateway[<NUM>]: <error> tls handshake failed client_ip=<IP> error=certificate_expired,91
32,E0033,<NUM>-<NUM>-<NUM> <TIME> error [inventory] bulk update failed: constraint violation on sku=ey-<NUM>,90
15,E0016,[<TIME>] i<PATH> payment processed order_id=ord-<NUM> amount=<NUM>.<NUM> currency=usd,87
9,E0010,<NUM>-<NUM>-<NUM> <TIME> info [payment-svc] payment method added uid=<NUM> type=card last4=<NUM>,85
21,E0022,<NUM>-<NUM>-<NUM> <TIME> info [payment-svc] refund initiated order_id=ord-<NUM> amount=<NUM>.<NUM>,84
25,E0026,mar <NUM> <TIME> prod-web-<NUM> payment-svc[<NUM>]: <info> invoice generated invoice_id=inv-<NUM>,79
55,E0056,"<NUM>-<NUM>-15t06:<NUM>:<NUM>.777427z warn scheduler: job queue backlog: <NUM> jobs pending, oldest=12min",79
18,E0019,<NUM>-<NUM>-15t06:<NUM>:<NUM>.709534z warn api-gateway: upstream timeout upstream=inventory duration=5000ms,69
36,E0037,<NUM>-<NUM>-15t06:<NUM>:<NUM>.981574z warn inventory: inventory discrepancy detected sku=gw-<NUM> expected=<NUM> actual=<NUM>,66
27,E0028,<NUM>-<NUM>-<NUM> <TIME> warn [payment-svc] slow response from payment gateway latency=53ms,64
24,E0025,"{""ts"": ""<NUM>-<NUM>-15t06:<NUM>:<NUM>.988078z"", ""level"": ""info"", ""svc"": ""payment-svc"", ""msg"": ""payment processed order_id=ord-<NUM> amount=<NUM>.<NUM> currency=usd"", ""trace_id"": ""trace-<NUM>""}",63
40,E0041,<NUM>-<NUM>-<NUM> <TIME> error [email-service] email send failed to=user606@outlook.com error=invalid_recipient,62
7,E0008,[<TIME>] i<PATH> request completed method=get path=<PATH> status=<NUM> duration=49ms,61
43,E0044,<NUM>-<NUM>-<NUM> <TIME> warn [auth-service] rate limit approaching for ip <IP>,60
60,E0061,"[<TIME>] e<PATH> scheduler heartbeat missed, possible zombie process pid=<NUM>",56
17,E0018,mar <NUM> <TIME> prod-web-<NUM> payment-svc[<NUM>]: <error> payment gateway returned http <NUM> endpoint=api.stripe.internal<PATH>,53
35,E0036,"<NUM>-<NUM>-15t06:<NUM>:<NUM>.977544z warn payment-svc: currency conversion rate stale, using cached value",52
16,E0017,<NUM>-<NUM>-15t06:<NUM>:<NUM>.298837z error auth-service: ldap connection refused host=ldap-primary.internal:<NUM>,51
31,E0032,"{""ts"": ""<NUM>-<NUM>-15t06:<NUM>:<NUM>.912949z"", ""level"": ""warn"", ""svc"": ""scheduler"", ""msg"": ""cron job slow job=daily_report_generation duration=<NUM>.3s threshold=60s"", ""trace_id"": ""trace-<NUM>""}",51
50,E0051,<NUM>-<NUM>-15t06:<NUM>:<NUM>.665890z error payment-svc: payment declined order_id=ord-<NUM> reason=insufficient_funds,48
19,E0020,"{""ts"": ""<NUM>-<NUM>-15t06:<NUM>:<NUM>.962935z"", ""level"": ""info"", ""svc"": ""email-service"", ""msg"": ""email sent to=user430@company.io template=welcome msg_id=msg-<NUM>""}",43
65,E0066,<NUM><PATH> +<NUM> | error | email-service | smtp relay refused: rate limit exceeded,43
37,E0038,<NUM><PATH> +<NUM> | error | inventory | warehouse api unreachable warehouse=wh-<NUM> error=econnrefused,42
53,E0054,<NUM>-<NUM>-<NUM> <TIME> error [auth-service] token signing key rotation failed: keystore locked,42
49,E0050,[<TIME>] e<PATH> cron job failed job=nightly_backup error=disk_space_insufficient path=<PATH> free=128mb,42
48,E0049,<NUM>-<NUM>-<NUM> <TIME> error [scheduler] job execution timeout job=data_migration after 300s,40
42,E0043,"{""ts"": ""<NUM>-<NUM>-15t06:<NUM>:<NUM>.030795z"", ""level"": ""error"", ""svc"": ""email-service"", ""msg"": ""template rendering failed template=invoice_v2 error=missing variable 'company_name'"", ""trace_id"": ""trace-<NUM>""}",37
29,E0030,"<NUM>-<NUM>-<NUM> <TIME> warn [email-service] smtp connection pool exhausted, waiting for available connection",37
34,E0035,"<NUM>-<NUM>-15t06:<NUM>:<NUM>.256023z error payment-svc: deadlock detected on transactions table, rolling back txn=txn-<NUM>",32
30,E0031,<NUM>-<NUM>-15t06:<NUM>:<NUM>.956887z info scheduler: scheduled task registered job=nightly_backup next_run=<TIME>,29
56,E0057,<NUM><PATH> +<NUM> | warn | email-service | bounce detected to=user765@gmail.com type=soft reason=mailbox_full,29
26,E0027,mar <NUM> <TIME> prod-web-<NUM> payment-svc[<NUM>]: <warn> payment retry scheduled order_id=ord-<NUM> attempt=<NUM><PATH>,27
47,E0048,"{""ts"": ""<NUM>-<NUM>-15t06:<NUM>:<NUM>.218644z"", ""level"": ""error"", ""svc"": ""payment-svc"", ""msg"": ""connection timeout to db-replica-<NUM> after 30000ms""}",27
78,E0079,[<TIME>] e<PATH> circuit breaker open for upstream=payment-svc failures=<NUM><PATH>,24
62,E0063,[<TIME>] w<PATH> session nearing expiry uid=<NUM> remaining=120s,24
69,E0070,"{""ts"": ""<NUM>-<NUM>-15t06:<NUM>:<NUM>.037605z"", ""level"": ""error"", ""svc"": ""scheduler"", ""msg"": ""cron job failed job=nightly_backup error=disk_space_insufficient path=<PATH> free=128mb"", ""trace_id"": ""trace-<NUM>""}",22
57,E0058,"{""ts"": ""<NUM>-<NUM>-15t06:<NUM>:<NUM>.327418z"", ""level"": ""info"", ""svc"": ""payment-svc"", ""msg"": ""invoice generated invoice_id=inv-<NUM>""}",17
33,E0034,"{""ts"": ""<NUM>-<NUM>-15t06:<NUM>:<NUM>.953211z"", ""level"": ""info"", ""svc"": ""inventory"", ""msg"": ""shipment received shipment_id=shp-<NUM> items=<NUM>""}",17
45,E0046,[<TIME>] i<PATH> health check passed upstream=inventory,17
20,E0021,[<TIME>] i<PATH> user login successful uid=<NUM>,17
75,E0076,"{""ts"": ""<NUM>-<NUM>-15t06:<NUM>:<NUM>.379825z"", ""level"": ""warn"", ""svc"": ""payment-svc"", ""msg"": ""currency conversion rate stale, using cached value"", ""trace_id"": ""trace-<NUM>""}",15
28,E0029,[<TIME>] w<PATH> rate limit exceeded client_id=app-<NUM> limit=<NUM><PATH>,14
5,E0006,[<TIME>] i<PATH> password reset requested uid=<NUM>,13
61,E0062,"[<TIME>] w<PATH> currency conversion rate stale, using cached value",12
22,E0023,"{""ts"": ""<NUM>-<NUM>-15t06:<NUM>:<NUM>.501809z"", ""level"": ""error"", ""svc"": ""inventory"", ""msg"": ""warehouse api unreachable warehouse=wh-<NUM> error=econnrefused"", ""trace_id"": ""trace-<NUM>""}",12
84,E0085,"[<TIME>] w<PATH> smtp connection pool exhausted, waiting for available connection",11
54,E0055,[<TIME>] i<PATH> invoice generated invoice_id=inv-<NUM>,11
89,E0090,"{""ts"": ""<NUM>-<NUM>-15t07:<NUM>:<NUM>.691763z"", ""level"": ""error"", ""svc"": ""email-service"", ""msg"": ""email send failed to=user710@outlook.com error=invalid_recipient""}",11
79,E0080,"{""ts"": ""<NUM>-<NUM>-15t07:<NUM>:<NUM>.351002z"", ""level"": ""error"", ""svc"": ""scheduler"", ""msg"": ""job execution timeout job=data_migration after 300s""}",10
44,E0045,[<TIME>] i<PATH> token refreshed for uid=<NUM>,9
38,E0039,[<TIME>] i<PATH> session created for uid=<NUM> ttl=<NUM>,9
73,E0074,[<TIME>] i<PATH> user logout uid=<NUM>,8
58,E0059,panic: runtime error: index out of range [<NUM>] with length <NUM>,7
81,E0082,"{""ts"": ""<NUM>-<NUM>-15t07:<NUM>:<NUM>.581463z"", ""level"": ""error"", ""svc"": ""auth-service"", ""msg"": ""token signing key rotation failed: keystore locked""}",7
80,E0081,[<TIME>] e<PATH> token signing key rotation failed: keystore locked,7
41,E0042,"main.processbatch(0xc0001a2000, 0x7, 0x10)",7
87,E0088,[<TIME>] w<PATH> rate limit approaching for ip <IP>,6
77,E0078,"{""ts"": ""<NUM>-<NUM>-15t06:<NUM>:<NUM>.718984z"", ""level"": ""warn"", ""svc"": ""payment-svc"", ""msg"": ""payment retry scheduled order_id=ord-<NUM> attempt=<NUM><PATH>",6
92,E0093,<PATH> +0x3a7,5
86,E0087,"{""ts"": ""<NUM>-<NUM>-15t07:<NUM>:<NUM>.093450z"", ""level"": ""error"", ""svc"": ""scheduler"", ""msg"": ""scheduler heartbeat missed, possible zombie process pid=<NUM>""}",5
70,E0071,==> switching to log rotation <==,5
72,E0073,goroutine <NUM> [running]:,5
82,E0083,[<TIME>] w<PATH> sync delay from erp: last update <NUM> minutes ago,4
68,E0069,"{""ts"": ""<NUM>-<NUM>-15t06:<NUM>:<NUM>.916670z"", ""level"": ""warn"", ""svc"": ""email-service"", ""msg"": ""smtp connection pool exhausted, waiting for available connection""}",4
51,E0052,[<TIME>] e<PATH> connection timeout to db-replica-<NUM> after 30000ms,4
66,E0067,[<TIME>] w<PATH> upstream timeout upstream=inventory duration=5000ms,4
64,E0065,"{""ts"": ""<NUM>-<NUM>-15t06:<NUM>:<NUM>.142723z"", ""level"": ""warn"", ""svc"": ""payment-svc"", ""msg"": ""slow response from payment gateway latency=168ms""}",4
39,E0040,"{""ts"": ""<NUM>-<NUM>-15t06:<NUM>:<NUM>.375174z"", ""level"": ""warn"", ""svc"": ""email-service"", ""msg"": ""bounce detected to=user867@gmail.com type=soft reason=mailbox_full""}",3
59,E0060,"{""ts"": ""<NUM>-<NUM>-15t06:<NUM>:<NUM>.984644z"", ""level"": ""error"", ""svc"": ""payment-svc"", ""msg"": ""payment declined order_id=ord-<NUM> reason=insufficient_funds""}",3
74,E0075,[<TIME>] w<PATH> slow response from payment gateway latency=234ms,3
52,E0053,null,3
67,E0068,"[<TIME>] e<PATH> deadlock detected on transactions table, rolling back txn=txn-<NUM>",2
95,E0096,[<TIME>] e<PATH> request entity too large method=post path=<PATH> size=<NUM> limit=<NUM>,2
94,E0095,"{""ts"": ""<NUM>-<NUM>-15t08:<NUM>:<NUM>.133109z"", ""level"": ""error"", ""svc"": ""api-gateway"", ""msg"": ""tls handshake failed client_ip=<IP> error=certificate_expired"", ""trace_id"": ""trace-<NUM>""}",2
90,E0091,"<NUM><PATH> +<NUM> | error | payment-svc | data integrity alert: checksum mismatch on transaction log segment 0x4f2a, possible corruption",2
76,E0077,???unexpected binary data??? \x00\x1f\x8b\x08,1
97,E0098,<NUM>-<NUM>-15t08:<NUM>:<NUM>.019621z error kernel: kernel panic: unable to handle page fault at ffffffff81a00000 cpu#<NUM>,1
96,E0097,mar <NUM> <TIME> prod-web-<NUM> auth-service[<NUM>]: <warn> unusual login pattern detected: uid=<NUM> logged in from <NUM> countries in <NUM> hours,1
93,E0094,<NUM>-<NUM>-<NUM> <TIME> warn [email-service] dns resolution intermittent for smtp.provider.com - <NUM> failures in last 60s,1
88,E0089,########## log restart ##########,1
91,E0092,"<NUM><PATH> +<NUM> | error | api-gateway | memory usage critical: <NUM>.<NUM>% of 16gb heap consumed, gc unable to free sufficient memory",1
63,E0064,^c,1
85,E0086,"<NUM>-<NUM>-<NUM> <TIME> warn [api-gateway] unexpected protocol: received http<PATH> request on http<PATH> listener, connection reset",1
83,E0084,--- connection reset ---,1
71,E0072,"<NUM>-<NUM>-<NUM> <TIME> error [inventory] cascade failure: warehouse sync triggered <NUM>,<NUM> duplicate sku entries in <NUM>.3s",1
98,E0099,"{""ts"": ""<NUM>-<NUM>-15t08:<NUM>:<NUM>.811781z"", ""level"": ""error"", ""svc"": ""auth-service"", ""msg"": ""certificate pinning violation detected from client_ip=<IP>, possible mitm attack""}",1

Total logs: 5195
Total unique Event IDs: 99
Average logs per Event ID: 52

In [61]:
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None)

from IPython.display import display, HTML

display(HTML("""
<style>
.dataframe {
    max-height: 500px;
    overflow-y: scroll;
    display: block;
}
</style>
"""))

# 🔥 Only first 50 rows (clean + fast)
display(df_final.head(50).style.set_properties(**{
    'white-space': 'pre-wrap',
    'text-align': 'left'
}))

# 🔥 Optional: last 50 for comparison
display(df_final.tail(50).style.set_properties(**{
    'white-space': 'pre-wrap',
    'text-align': 'left'
}))

In [62]:
# Count frequency of each Event ID
event_counts = df['event_id'].value_counts().reset_index()
event_counts.columns = ['event_id', 'count']

# ✅ Take only ONE template per event_id (most frequent one)
event_templates = df.groupby('event_id')['template'].agg(lambda x: x.mode()[0]).reset_index()

# Merge correctly
event_counts = event_counts.merge(event_templates, on='event_id', how='left')

# Reorder
event_counts = event_counts[['event_id', 'template', 'count']]

# Attach back to main df (safe way)
df = df.drop(columns=['count', 'rare_event'], errors='ignore')
count_dict = event_counts.set_index('event_id')['count'].to_dict()
df['count'] = df['event_id'].map(count_dict)

# Rare events
RARE_THRESHOLD = 5
df['rare_event'] = df['count'] < RARE_THRESHOLD

# Display clean output
print("Top Events:")
display(event_counts.sort_values(by='count', ascending=False).head(20))

print("\nRare Events:")
display(event_counts.sort_values(by='count', ascending=True).head(20))

Top Events:

,event_id,template,count
0,E0005,<NUM>-<NUM>-<NUM> <TIME> info [auth-service] token refreshed for uid=<NUM>,710
1,E0002,<NUM>-<NUM>-<NUM> <TIME> warn [api-gateway] rate limit exceeded client_id=app-<NUM> limit=<NUM><PATH>,500
2,E0009,<NUM>-<NUM>-<NUM> <TIME> error [api-gateway] request entity too large method=post path=<PATH> size=<NUM> limit=<NUM>,311
3,E0001,<NUM>-<NUM>-<NUM> <TIME> info [api-gateway] health check passed upstream=auth-service,305
4,E0007,<NUM>-<NUM>-<NUM> <TIME> info [email-service] email sent to=user187@company.io template=welcome msg_id=msg-<NUM>,192
5,E0014,<NUM>-<NUM>-<NUM> <TIME> warn [scheduler] cron job slow job=daily_report_generation duration=<NUM>.3s threshold=60s,144
6,E0003,<NUM>-<NUM>-<NUM> <TIME> info [inventory] inventory sync completed source=erp records=<NUM> duration=<NUM>.4s,134
7,E0012,"{""ts"": ""<NUM>-<NUM>-15t06:<NUM>:<NUM>.002701z"", ""level"": ""info"", ""svc"": ""auth-service"", ""msg"": ""user logout uid=<NUM>""}",131
8,E0015,<NUM><PATH> +<NUM> | error | inventory | failed to reserve stock sku=dz-<NUM> requested=<NUM> available=<NUM>,131
9,E0004,<NUM>-<NUM>-<NUM> <TIME> info [inventory] stock updated sku=cw-<NUM> qty=<NUM> warehouse=wh-<NUM>,124
10,E0047,<NUM>-<NUM>-<NUM> <TIME> info [email-service] email queue drained: <NUM> pending,117
11,E0011,<NUM>-<NUM>-<NUM> <TIME> info [inventory] shipment received shipment_id=shp-<NUM> items=<NUM>,99
12,E0013,<NUM>-<NUM>-<NUM> <TIME> info [inventory] reorder triggered sku=cx-<NUM> qty_ordered=<NUM>,92
13,E0024,<NUM>-<NUM>-<NUM> <TIME> error [api-gateway] tls handshake failed client_ip=<IP> error=certificate_expired,91
14,E0033,<NUM>-<NUM>-<NUM> <TIME> error [inventory] bulk update failed: constraint violation on sku=dw-<NUM>,90
15,E0016,<NUM>-<NUM>-<NUM> <TIME> info [payment-svc] payment processed order_id=ord-<NUM> amount=<NUM>.<NUM> currency=usd,87
16,E0010,<NUM>-<NUM>-<NUM> <TIME> info [payment-svc] payment method added uid=<NUM> type=card last4=<NUM>,85
17,E0022,<NUM>-<NUM>-<NUM> <TIME> info [payment-svc] refund initiated order_id=ord-<NUM> amount=<NUM>.<NUM>,84
18,E0026,<NUM>-<NUM>-<NUM> <TIME> info [payment-svc] invoice generated invoice_id=inv-<NUM>,79
19,E0056,"<NUM>-<NUM>-<NUM> <TIME> warn [scheduler] job queue backlog: <NUM> jobs pending, oldest=12min",79

Rare Events:

,event_id,template,count
98,E0099,"{""ts"": ""<NUM>-<NUM>-15t08:<NUM>:<NUM>.811781z"", ""level"": ""error"", ""svc"": ""auth-service"", ""msg"": ""certificate pinning violation detected from client_ip=<IP>, possible mitm attack""}",1
88,E0064,^c,1
89,E0072,"<NUM>-<NUM>-<NUM> <TIME> error [inventory] cascade failure: warehouse sync triggered <NUM>,<NUM> duplicate sku entries in <NUM>.3s",1
90,E0077,???unexpected binary data??? \x00\x1f\x8b\x08,1
91,E0084,--- connection reset ---,1
97,E0098,<NUM>-<NUM>-15t08:<NUM>:<NUM>.019621z error kernel: kernel panic: unable to handle page fault at ffffffff81a00000 cpu#<NUM>,1
93,E0089,########## log restart ##########,1
94,E0092,"<NUM><PATH> +<NUM> | error | api-gateway | memory usage critical: <NUM>.<NUM>% of 16gb heap consumed, gc unable to free sufficient memory",1
95,E0094,<NUM>-<NUM>-<NUM> <TIME> warn [email-service] dns resolution intermittent for smtp.provider.com - <NUM> failures in last 60s,1
96,E0097,mar <NUM> <TIME> prod-web-<NUM> auth-service[<NUM>]: <warn> unusual login pattern detected: uid=<NUM> logged in from <NUM> countries in <NUM> hours,1
92,E0086,"<NUM>-<NUM>-<NUM> <TIME> warn [api-gateway] unexpected protocol: received http<PATH> request on http<PATH> listener, connection reset",1
87,E0096,[<TIME>] e<PATH> request entity too large method=post path=<PATH> size=<NUM> limit=<NUM>,2
86,E0095,"{""ts"": ""<NUM>-<NUM>-15t08:<NUM>:<NUM>.133109z"", ""level"": ""error"", ""svc"": ""api-gateway"", ""msg"": ""tls handshake failed client_ip=<IP> error=certificate_expired"", ""trace_id"": ""trace-<NUM>""}",2
85,E0091,"<NUM><PATH> +<NUM> | error | payment-svc | data integrity alert: checksum mismatch on transaction log segment 0x4f2a, possible corruption",2
84,E0068,"[<TIME>] e<PATH> deadlock detected on transactions table, rolling back txn=txn-<NUM>",2
80,E0040,"{""ts"": ""<NUM>-<NUM>-15t06:<NUM>:<NUM>.251933z"", ""level"": ""warn"", ""svc"": ""email-service"", ""msg"": ""bounce detected to=user761@example.org type=soft reason=mailbox_full""}",3
82,E0060,"{""ts"": ""<NUM>-<NUM>-15t06:<NUM>:<NUM>.984644z"", ""level"": ""error"", ""svc"": ""payment-svc"", ""msg"": ""payment declined order_id=ord-<NUM> reason=insufficient_funds""}",3
83,E0075,[<TIME>] w<PATH> slow response from payment gateway latency=180ms,3
81,E0053,null,3
79,E0083,[<TIME>] w<PATH> sync delay from erp: last update <NUM> minutes ago,4

In [63]:
import re

def extract_severity(log):
    log = log.lower()
    
    if "error" in log:
        return "ERROR"
    elif "warn" in log:
        return "WARN"
    elif "info" in log:
        return "INFO"
    else:
        return "UNKNOWN"

df["severity"] = df["raw_log"].apply(extract_severity)

display(df[["raw_log", "severity"]].head(20))

,raw_log,severity
0,mar 15 06:00:03 prod-app-01 api-gateway[3330]: <info> health check passed upstream=auth-service,INFO
1,2026-03-15 06:00:03 info [api-gateway] request completed method=get path=/api/v2/users/3591 status=200 duration=264ms,INFO
2,2026-03-15 06:00:07 warn [inventory] sync delay from erp: last update 47 minutes ago,WARN
3,2026-03-15 06:00:09 info [inventory] stock updated sku=gw-7547 qty=328 warehouse=wh-03,INFO
4,2026-03-15t06:00:11.927231z error auth-service: mfa verification failed uid=2160 code=invalid,ERROR
5,2026-03-15 06:00:14 warn [api-gateway] request slow method=get path=/api/v2/search status=200 duration=2021ms,WARN
6,[06:00:17] i/auth-service: password reset requested uid=9085,UNKNOWN
7,mar 15 06:00:21 prod-app-01 inventory[4727]: <info> inventory sync completed source=erp records=2847 duration=12.4s,INFO
8,[06:00:25] i/email-service: email sent to=user677@company.io template=welcome msg_id=msg-739098,UNKNOWN
9,[06:00:28] i/api-gateway: request completed method=get path=/api/v2/products status=200 duration=49ms,UNKNOWN
10,"{""ts"": ""2026-03-15t06:00:29.047373z"", ""level"": ""info"", ""svc"": ""api-gateway"", ""msg"": ""health check passed upstream=inventory""}",INFO
11,2026-03-15 06:00:33 info [payment-svc] payment method added uid=9834 type=card last4=6352,INFO
12,2026-03-15 06:00:37 info [inventory] shipment received shipment_id=shp-58689 items=48,INFO
13,"{""ts"": ""2026-03-15t06:00:37.842791z"", ""level"": ""info"", ""svc"": ""auth-service"", ""msg"": ""user logout uid=1514""}",INFO
14,2026-03-15 06:00:40 info [inventory] reorder triggered sku=dx-8478 qty_ordered=500,INFO
15,2026-03-15 06:00:44 warn [scheduler] cron job slow job=daily_report_generation duration=145.3s threshold=60s,WARN
16,2026-03-15 06:00:48 warn [auth-service] session nearing expiry uid=4527 remaining=120s,WARN
17,[06:00:50] i/email-service: email sent to=user255@company.io template=order_confirmation msg_id=msg-219971,UNKNOWN
18,"{""ts"": ""2026-03-15t06:00:53.761702z"", ""level"": ""info"", ""svc"": ""api-gateway"", ""msg"": ""request completed method=get path=/api/v2/products status=200 duration=142ms""}",INFO
19,mar 15 06:00:56 prod-web-01 auth-service[5564]: <info> mfa verification passed uid=7669,INFO

In [64]:
severity_map = {
    "ERROR": 3,
    "WARN": 2,
    "INFO": 1,
    "UNKNOWN": 0
}

df["severity_score"] = df["severity"].map(severity_map)

In [ ]:
# Map severity score to readable label
def severity_label(avg):
    if avg >= 2.5:
        return "HIGH (Mostly ERROR)"
    elif avg >= 1.5:
        return "MEDIUM (WARN/ERROR mix)"
    elif avg >= 0.5:
        return "LOW (Mostly INFO)"
    else:
        return "INFO/UNKNOWN"

# Event level aggregation
event_severity = df.groupby("event_id").agg({
    "severity_score": "mean",
    "count": "first",
    "template": "first"
}).reset_index()

# Rename column
event_severity.rename(columns={"severity_score": "avg_severity"}, inplace=True)

# Add readable severity column
event_severity["severity_label"] = event_severity["avg_severity"].apply(severity_label)

# 🔥 Scrollable display
from IPython.display import display, HTML

display(HTML("""
<style>
.dataframe {
    max-height: 500px;
    overflow-y: scroll;
    display: block;
}
</style>
"""))

pd.set_option('display.max_colwidth', None)

display(event_severity.style.set_properties(**{
    'white-space': 'pre-wrap',
    'text-align': 'left'
}))

In [66]:
# Normalize count (low count = more anomalous)
event_severity["count_score"] = 1 / event_severity["count"]

# Final anomaly score
event_severity["anomaly_score"] = (
    event_severity["avg_severity"] * 0.7 + 
    event_severity["count_score"] * 0.3
)

In [68]:
# 🔹 Define readable anomaly level
def anomaly_label(score):
    if score >= 2.0:
        return "CRITICAL 🔥 (Frequent errors or severe rare issue)"
    elif score >= 1.2:
        return "HIGH ⚠️ (Important issue, needs attention)"
    elif score >= 0.5:
        return "MEDIUM ⚡ (Moderate anomaly)"
    else:
        return "LOW ✅ (Mostly normal behavior)"

# 🔹 Add label column
event_severity["anomaly_label"] = event_severity["anomaly_score"].apply(anomaly_label)

# 🔹 Sort anomalies
anomalies = event_severity.sort_values(by="anomaly_score", ascending=False)

print("🚨 Top Anomalies:")

# 🔥 Scrollable display (NOT limited to head)
from IPython.display import display, HTML

display(HTML("""
<style>
.dataframe {
    max-height: 500px;
    overflow-y: auto;
    overflow-x: auto;
    display: block;
}
</style>
"""))

pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None)

display(anomalies.style.set_properties(**{
    'white-space': 'pre-wrap',
    'text-align': 'left'
}))

🚨 Top Anomalies: